# Generated by Django 2.2.6 on 2021-02-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20210228_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='key',
        ),
        migrations.AddField(
            model_name='article',
            name='id',
            field=models.AutoField(auto_created=True, default=999, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
