# Generated by Django 2.2.6 on 2021-02-28 16:09

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20210228_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.AddField(
            model_name='article',
            name='contents',
            field=markdownx.models.MarkdownxField(default=0, help_text='To Write with Markdown format', verbose_name='Contents'),
            preserve_default=False,
        ),
    ]
