# Generated by Django 2.2.6 on 2021-03-01 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_article_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='contents',
        ),
    ]
