# Generated by Django 2.2.6 on 2021-03-01 10:22

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_remove_article_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='contents',
            field=mdeditor.fields.MDTextField(default=1),
            preserve_default=False,
        ),
    ]
