# Generated by Django 2.2.6 on 2021-03-01 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_article_contents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='contents',
            new_name='content',
        ),
    ]
