# Generated by Django 2.2.6 on 2021-03-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_comment_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='approved',
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=True, to='article.Article'),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
