# Generated by Django 2.2.6 on 2021-03-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='comment',
            field=models.ForeignKey(on_delete=True, related_name='replies', to='article.Comment'),
        ),
    ]
